version: "2"
networks:
  peopletracker:
    driver: bridge
services:
  mongodb:
    image: "bitnami/mongodb:4.0"
    ports:
      - "28018:27017"
    volumes:
      - "mongodb_data:/bitnami"
    networks:
      - peopletracker
volumes:
  mongodb_data:
    driver: local
